projects:
  app:
    schemaPath: "schema.graphql"
    extensions:
      endpoints:
      default: "http://localhost:4000"
  prisma:
    schemaPath: "src/generated/"
    extensions:
      prisma: "prisma.yml"
